version: '3.9'

services:

  vote:
    build:
      context: ./vote
      dockerfile: Dockerfile
      args:
        # 1. Tell the Dockerfile to build in 'dev' mode
        - APP_ENV=dev
        # 2. Pass build-time ARGs (using defaults is also fine)
        - REDIS_HOST=redis 
        - REDIS_PORT=6379
        - OPTION_A=Cats
        - OPTION_B=Dogs
      
    container_name: vote_service
    
    ports:
      - "9090:80"
    depends_on:
      - redis
    restart: always

  result:
    build:
      context: ./result
      dockerfile: Dockerfile
      args:
        - RESULT_PORT=4000
        - PGUSER=postgres
        - PGPASSWORD=postgres
        - PGDATABASE=postgres
        - PGHOST=db
        - PGPORT=5432
    container_name: result_service
    ports:
      - "9091:4000"
    depends_on:
      - db

  redis:
    image: redis:7
    container_name: redis_service
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  db:
    image: postgres:15-alpine
    container_name: db_service
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  redis_data:
  db_data:


